require('vim._core.ui2').enable()
require('config.options')
require('config.extra_options')
require('config.lsp')
require('config.lazy')
require('config.autocmds')
require('config.usercmds')
require('config.keymaps')
